accounts/urls.py
from django.urls import path, include
from django.contrib.auth.views import LoginView, LogoutView
from .views import register

urlpatterns = [
  # path('', include('django.contrib.auth.urls')),

    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(template_name='registration/logout.html'), name='logout'),
    path('register/', register, name='register')
]

config/urls.py
from django.contrib import admin
from django.urls import path
#여기가 학교 정문
from django.contrib import admin
from django.urls import path, include
from rest_framework_swagger.views import get_swagger_view
from rest_framework.authtoken import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('photo.urls')),

    path('accounts/', include('accounts.urls')),
    path('api/doc/', get_swagger_view(title='Dstagram API Manual')),
    path('api/get/token/', views.obtain_auth_token),



]

from django.conf.urls.static import static
from  django.conf import settings

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

photo/urls.py
#url들 있을거에여 여기에!

from django.urls import path
from .views import *
app_name = 'photo'

#메인 유알엘에서 여기로 들어 올 수 있게 해야해! ex) 학교문 통과해야 기숙사문을 여는데 우린 지금 기숙사 문만 만든거임
urlpatterns = [
   path('detail/<int:pk>/', PhotoDetailView.as_view(), name='photo_detail'),
   path('', PhotoListView.as_view(), name='index'),
   path('upload/', PhotoUploadView.as_view(), name='photo_upload'),
   path('update/<int:pk>/', PhotoUpdateView.as_view(), name='photo_update'), #몇번을 수정할지 알려줘야하니까 인트 pk있는게 ㅗㅈㅎ을듯
   path('delete/<int:pk>/', PhotoDeleteView.as_view(), name='photo_delete'),
   path('tag/<tag>/', TaggedPhotoListView.as_view(), name='tagged_photo_list'),
   path('tag/', TagListView.as_view(), name='tag_list'),


   path('photo/', PhotoList.as_view()),
   path('photo/<int:pk>/', PhotoDetail.as_view()),

]

accounts/models.py
from django.db import models

# Create your models here.

board/models.py
from django.db import models

# Create your models here.

photo/models.py
from django.db import models
from django.contrib.auth import get_user_model
from django.urls import reverse_lazy
from tagging.fields import TagField
# Create your models here.

class Photo(models.Model):
    # 외래키 -> 참조키!!! 외래키 설정할 때는 어떤 모델의 주 키를 사용할건지 정해야함 장고 규칙임
    author = models.ForeignKey(get_user_model(), on_delete=models.CASCADE, related_name='image')
    #이렇게 동적으로 가져 올 수 있음 (user의 기본 설정은 아이디 비번 이메일 더 이상 하려면 기본을 확장해야함 저건 바뀔 수 있으니까 유저모델이라는 매소드 사용
    #on delete는 유저를 삭제하면 같이 올라간 애들을 어쩔거냐고 물어보는거임
    #cascad는 유저 지우면 포토도 다 지우겠다는 거임
    #related name은 내 페이지에서 내꺼만 뜨게 하려고 쓰는거 나라는 객체.이미지스 하면 내가 올린이미지만 뙇 하고 나옴
    #파이썬에서 사진 쓰려면 pip install pillow (터미널에 이렇게! 해서


    image = models.ImageField(upload_to='images/%Y/%m/%d')
    text = models.TextField(blank=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    tag = TagField()

    class Meta: #innerclass 옵션 클래스라고 생각해도 갠춘할듯
        ordering = ['-updated'] #최신 업데이트 된 애들부터 데려오겠다! (db옵션 )
        #db에 적용할 변경사항 찾기  python manage.py makemigrations photo
        #해당 변경사항 적용하기     python manage.py migrate photo
    def __str__(self):
        return self.author.username + " "+self.created.strftime("%Y -%m-%d %H :%M:%S")

    def get_absolute_url(self):
        return reverse_lazy('photo:photo_detail', args=[self.id])

#모델의 역할은 디비에 어떻게 할건지 하는고야 두번쨰 쓰는것같은데 그러하다고 한다음에는 터미널에서 migrate

#json 어떻게 제공할지 정해야함

accounts/forms.py
from django.contrib.auth import get_user_model
from django import forms

class RForm(forms.ModelForm):
    password = forms.CharField(label='Password', widget=forms.PasswordInput) #widget비번*로 보이는것같은거
    password2 = forms.CharField(label='Password', widget=forms.PasswordInput)

    class Meta:
        model=get_user_model()
        fields = ('username', 'first_name', 'last_name', 'email')
        def clean_password2(self):
            cd = self.clean_data
            if cd['password'] != cd['password2'] :
                raise forms.ValidationError("password doesn't match. ")

            return cd['password2']

accounts/views.py
from django.shortcuts import render

# Create your views here.

# TODO : 회원가입 만들거임!
from .forms import RForm
def register(request):
    if request.method == 'POST':
        #회원가입 정보 입력 후
        user_form = RForm(request.POST)
        if user_form.is_valid():
            new_user = user_form.save(commit=False)                     #db에 저장하지말고 메모리에서만 만들어라! 인스턴스만 만들라는소리 비번을 아직 안했으니까
            new_user.set_password(user_form.cleaned_data['password'])   #비번 암호화 해서 저장하려는것
            new_user.save() #이때 db에 저장되는거임
            return render(request, 'registration/register_done.html', {'new_user': new_user})

    else:
        # 회원가입 정보 입력받을 때
        user_form = RForm()

    return render(request, 'registration/register.html', {'form': user_form})

        #form.as_p의 이름이 이 때 정해짐

board/views.py
from django.shortcuts import render

# Create your views here.

photo/views.py
from django.shortcuts import render
from .models import Photo
# Create your views here.

from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from  django.contrib.auth.mixins import LoginRequiredMixin
#믹스인,데코레이터 : 접근 권한 제어, 뷰를 실행하기에 앞서 특별한 기능을 붙이는 역할을 함
#믹스인-> 클래스형 뷰
#데코레이터->함수형 뷰

class PhotoListView(LoginRequiredMixin, ListView):
    model = Photo
    template_name = 'photo/list.html'



class PhotoDetailView(DetailView):
    model = Photo
    template_name = 'photo/detail.html'


from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.shortcuts import redirect



class PhotoUploadView(LoginRequiredMixin, CreateView):
    model = Photo
    fields = ['image', 'text']
    template_name = 'photo/upload.html'

    def form_valid(self, form): #세이브 전 폼 정보가 올바른지
        form.instance.author_id = self.request.user.id
        if form.is_valid():
            form.instance.save()
            return redirect('/')
        else:
            return self.render_to_response({'form': form})


class PhotoUpdateView(LoginRequiredMixin, UpdateView):
    model = Photo
    fields = ['image', 'text']
    template_name = 'photo/update.html'
    # success_url = '/' 보통은 이렇게 완료하면 시작페이지로! ㅎ ㅏ지만 우린 모델을 만질거랍니닷!

class PhotoDeleteView(LoginRequiredMixin, DeleteView):
    model = Photo
    template_name = 'photo/delete.html'
    success_url = '/'

from tagging.views import TaggedObjectList

class TaggedPhotoListView(TaggedObjectList):
    model = Photo
    template_name = 'photo/tagged_photo_list.html'

from django.views.generic import TemplateView

class TagListView(TemplateView):
    template_name = 'photo/tag_list.html'

#API view
from rest_framework import generics
from .serializers import PhotoSerializer
from rest_framework.authentication import TokenAuthentication
from rest_framework.permissions import IsAuthenticated

class PhotoList(generics.ListCreateAPIView):
    queryset = Photo.objects.all()
    serializer_class = PhotoSerializer

#추가하기가 되도록 하기 위함
class PhotoDetail(generics.RetrieveUpdateDestroyAPIView):
    queryset = Photo.objects.all()
    serializer_class = PhotoSerializer

    authentication_classes = (TokenAuthentication, ) #로그인을 어떤 방식을 제공할거임? 토큰방식으로할거임!
    permission_classes = (IsAuthenticated, IsAuthenticated)# 로그인을 한 사람만 쓸 수 있게 하겠다

photo/templates/photo/delete.html
{% extends 'base.html' %}

{% block content %}


        <div class = "row">
            <div class = "col-md-3"></div>
            <div class = "col-md-6 panel panel-default">

                <form action="" method="post" > <!--enctype="multipart/form-data 이게 빠져있으면 ㅝ가 안된다는것같은-->
                    <!--{{ form.as_p }} 이건 필요없음-->
                    <div class="alert alert-danger">Do you want delete {{ object }}</div>

                    {% csrf_token %}

                    <input type="submit" name="Delete" class="btn btn-danger">
                </form>


                </div>
            </div>
            <div class = "col-md-3"></div>
        </div>

{% endblock %}

photo/templates/photo/detail.html
{% extends 'base.html' %}

{% block content %}
    {% load tagging_tags %}

        <div class = "row">
            <div class = "col-md-2"></div>
            <div class = "col-md-8 panel panel-default">

                <div class="card align-self-center" >

                    <img src="{{object.image.url}}" class="card-img-top" >

                    <div class="card-body">
                        <button class="btn btn-primary btn-sm">{{object.author.username}}</button>
                        <p class="card-text">{{object.text}}</p>

                        {% tags_for_object object as tags %}
                        {% if tags %}
                        <p>
                            {% tags_for_object object as tags %}
                            {% for tag in tags %}
                                <a href="{% url 'photo:tagged_photo_list' tag.name %}" >#{{tag.name}}</a> <!-- 해시태그가 없어도 보여줘버림  -->
                            {% endfor %}
                        </p>
                        {% endif %}

                        <a href="{% url 'photo:photo_delete' object.id %}" class="btn btn-outline-primary">Delete</a>
                        <a href="{% url 'photo:photo_update' object.id %}" class="btn btn-outline-warning">Update</a>
                        </div>
                </div>
            </div>
            <div class = "col-md-2"></div>
        </div>




<div class = "row">
            <div class = "col-md-2"></div>
            <div class = "col-md-8 panel panel-default">

               {% load disqus_tags %}
               {% disqus_show_comments %}




                </div>
            </div>
            <div class = "col-md-2"></div>
        </div>

{% endblock %}

photo/templates/photo/list.html
{% extends 'base.html' %}

{% block content %}
    {% load tagging_tags %}

    {% for object in object_list %}
        <div class = "row">
            <div class = "col-md-3"></div>
            <div class = "col-md-6 panel panel-default">

                <div class="card align-self-center" >

                    <img src="{{object.image.url}}" class="card-img-top" >

                    <div class="card-body">
                        <button class="btn btn-primary btn-sm">{{object.author.username}}</button>
                        <p class="card-text">{{object.text}}</p>

                        {% tags_for_object object as tags %}
                        {% if tags %}
                        <p>
                            {% tags_for_object object as tags %}
                            {% for tag in tags %}
                                <a href="{% url 'photo:tagged_photo_list' tag.name %}" >#{{tag.name}}</a> <!-- 해시태그가 없어도 보여줘버림  -->
                            {% endfor %}
                        </p>
                        {% endif %}

                        <a href="{% url 'photo:photo_detail' object.id %}" class="btn btn-outline-primary">Detail</a>
                    </div>
                </div>

            </div>
            <div class = "col-md-3"></div>
        </div>
    {% endfor %}
{% endblock %}

photo/templates/photo/tag_list.html
{% extends 'base.html' %}
{% block content %}
    {% load tagging_tags %}
    {% tag_cloud_for_model photo.Photo as tags %}

    {% for tag in tags %}

    <a href="{% url 'photo:tagged_photo_list' tag.name%}">#{{ tag.name }}</a>

    {% endfor %}

{% endblock %}

photo/templates/photo/tagged_photo_list.html
{% extends 'base.html' %}

{% block content %}
    {% load tagging_tags %}

    {% for object in object_list %}
        <div class = "row">
            <div class = "col-md-3"></div>
            <div class = "col-md-6 panel panel-default">

                <div class="card align-self-center" >

                    <img src="{{object.image.url}}" class="card-img-top" >

                    <div class="card-body">
                        <button class="btn btn-primary btn-sm">{{object.author.username}}</button>
                        <p class="card-text">{{object.text}}</p>

                        {% tags_for_object object as tags %}
                        {% if tags %}
                        <p>
                            {% tags_for_object object as tags %}
                            {% for tag in tags %}
                                <a href="{% url 'photo:tagged_photo_list' tag.name %}" >#{{tag.name}}</a> <!-- 해시태그가 없어도 보여줘버림  -->
                            {% endfor %}
                        </p>
                        {% endif %}

                        <a href="{% url 'photo:photo_detail' object.id %}" class="btn btn-outline-primary">Detail</a>
                    </div>
                </div>

            </div>
            <div class = "col-md-3"></div>
        </div>
    {% endfor %}
{% endblock %}

photo/templates/photo/update.html
{% extends 'base.html' %}

{% block content %}


        <div class = "row">
            <div class = "col-md-3"></div>
            <div class = "col-md-6 panel panel-default">

                <form action="" method="post" enctype="multipart/form-data"> <!--enctype="multipart/form-data 이게 빠져있으면 ㅝ가 안된다는것같은-->
                    {{ form.as_p }}
                    {% csrf_token %}

                    <input type="submit" name="Update" class="btn btn-success">
                </form>


                </div>
            </div>
            <div class = "col-md-3"></div>
        </div>

{% endblock %}

photo/templates/photo/upload.html
{% extends 'base.html' %}

{% block content %}


        <div class = "row">
            <div class = "col-md-3"></div>
            <div class = "col-md-6 panel panel-default">

                <form action="" method="post" enctype="multipart/form-data"> #<!--enctype="multipart/form-data 이게 빠져있으면 ㅝ가 안된다는것같은-->
                    {{ form.as_p }}
                    {% csrf_token %}

                    <input type="submit" name = "Upload" class="btn btn-success">
                </form>


                </div>
            </div>
            <div class = "col-md-3"></div>
        </div>

{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css" integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js" integrity="sha384-wHAiFfRlMFy6i5SRaxvfOCifBUQy1xHdJ/yoi7FRNXMRBu5WHdZYu1hA6ZOblgut" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js" integrity="sha384-B0UglyR+jN6CkvvICOB2joaf5I4l3gm9GU6Hc1og6Ls7i6U/mkkaduKaBhlAXv9k" crossorigin="anonymous"></script>

</head>
<body>
<div class="container">
    <header class="header clearfix">
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <a class="navbar-brand" href="/">Dstagram</a>
            <ul class="nav">
                <li class="nav-item">
                    <a href="/" class="active nav-link">Home</a>
                </li>

                {% if user.is_authenticated %}
                <li class="nav-item"><a href="#" class="active nav-link">Welcome, {{user.get_username}}</a></li>
                <li class="nav-item"><a href="{% url 'photo:tag_list' %}" class="active nav-link">tag</a></li>
                <li class="nav-item"><a href="{% url 'photo:photo_upload' %}" class="active nav-link">Upload</a></li>
                <li class="nav-item"><a href="{% url 'logout' %}" class="active nav-link">Logout</a></li>
                {% else %}
                <li class="nav-item"><a href="{% url 'register' %}" class="active nav-link">Register</a></li>
                <li class="nav-item"><a href="{% url 'login' %}" class="active nav-link">Login</a></li>
                {% endif %}

            </ul>
        </nav>
    </header>
{% block content %}

{% endblock %}
</div>
</body>
</html>